services:
  - type: web
    name: wms-ai-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
